# Generated by Django 3.0.5 on 2020-04-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_doc_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=250, verbose_name='Номер телефону')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('msg', models.TextField(verbose_name='Повідомлення')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Запис на прийом',
                'verbose_name_plural': 'Записи на прийом',
                'ordering': ('date',),
            },
        ),
    ]
