# Generated by Django 3.0.5 on 2020-04-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_auto_20200412_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
