# Generated by Django 3.0.5 on 2020-04-15 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0007_auto_20200415_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 15, 19, 57, 45, 769053), verbose_name='Дата'),
        ),
    ]
