# Generated by Django 3.0.5 on 2020-04-15 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0008_auto_20200415_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 15), verbose_name='Дата'),
        ),
    ]
