# Generated by Django 3.0.5 on 2020-04-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0009_auto_20200415_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='img/logo.png', upload_to='news/', verbose_name='Зображення'),
        ),
    ]
