# Generated by Django 3.0.5 on 2020-04-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0011_auto_20200417_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/', verbose_name='Зображення'),
        ),
    ]
