# Generated by Django 3.0.5 on 2020-04-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0012_auto_20200417_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Event',
        ),
    ]
