# Generated by Django 3.0.5 on 2020-04-18 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0013_auto_20200417_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'ordering': ('-id',), 'verbose_name': 'Лікар', 'verbose_name_plural': 'Лікарі'},
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 18), verbose_name='Дата'),
        ),
    ]
