# Generated by Django 3.0.5 on 2020-04-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0014_auto_20200418_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date', 'title'), 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
    ]
