# Generated by Django 3.0.5 on 2020-04-23 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0016_auto_20200420_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='text',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 23), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Посилання головна'),
        ),
    ]
